# Generated by Django 4.2.6 on 2023-10-24 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_string', models.CharField(max_length=250)),
                ('college', models.CharField(blank=True, max_length=2, null=True)),
                ('mealtime', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=21, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
