# Generated by Django 4.2.6 on 2023-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pref_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pref',
            name='day',
        ),
        migrations.AlterField(
            model_name='pref',
            name='college',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='pref',
            name='mealtime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pref',
            name='pref_string',
            field=models.CharField(max_length=300),
        ),
    ]
