# Generated by Django 4.2.6 on 2023-10-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pref_app', '0002_remove_pref_day_alter_pref_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pref',
            old_name='college',
            new_name='colleges',
        ),
        migrations.RenameField(
            model_name='pref',
            old_name='mealtime',
            new_name='mealtimes',
        ),
    ]
