# Generated by Django 4.2.6 on 2023-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pref_app', '0003_rename_college_pref_colleges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pref',
            name='colleges',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
