# Generated by Django 4.2.3 on 2023-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pref_app', '0005_remove_pref_colleges_remove_pref_mealtimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pref',
            name='breakfast',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pref',
            name='brunch_lunch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pref',
            name='dinner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
